### ISSUE TITLE
Please don't publish vendor bundled gems

### ISSUE THREAD

**Issue by mensfeld** [talon-one/talon_one.rb#20]
Hey, your rubygems release contains bundled pack: https://rubygems.org/gems/talon_one in vendor dir. You don't have to have it and it makes the releases much bigger and harder to review.

Would appreciate if you would release it without vendor. Thanks! <3

**Comment by altJake** [comment]
Hey @mensfeld , thanks for reporting this and letting us know!
It is definitely an oversight and not an intended behavior.

We are about to release a new version soon, and will make sure to solve this as part of it

**Comment by mensfeld** [comment]
Np problem. Thank you for fixing this.

FYI I found it when I've been looking and your release here: https://my.diffend.io/gems/talon_one/1.4.0/2.0.0

**Comment by altJake** [comment]
Will do, thanks for the offer.

And thanks for the reference - great resource 👌

**Comment by altJake** [comment]
@mensfeld if you want to have a look at the potential fix, I would love to hear if that feels correct from your perspective as well: 16957cd

**Comment by mensfeld** [comment]
@altJake looks great. You can check the integration (that it was pushed c orrectly) on the diffend page for the new release: https://my.diffend.io/gems/talon_one/2.0.0/2.1.0 

Expanding files changed list will show you that:

![Zrzut ekranu z 2020-05-29 10-21-49](https://user-images.githubusercontent.com/392754/83238097-3d125780-a196-11ea-8a45-9ec6501305b2.png)

all deleted. Great work!
