### ISSUE TITLE
Propose: improve error handling for API errors

### ISSUE THREAD

**Issue by cristianoliveira** [talon-one/talon_one.rb#6]
Hi 

We are currently running with some problems to handle properly the exceptions that occur when we use this client. For instance, when we try update the client session when it is already closed it raises:
```
RuntimeError: PUT /v1/customer_sessions/order_P67XJYD -> 400 {"message":"Cannot move session to state \"open\" from state \"closed\""}
- 2 non-project frames
1
File "/app/vendor/bundle/ruby/2.3.0/bundler/gems/talon-one.rb-250227210621/lib/integration/client.rb" line 34 in request
2
File "/app/vendor/bundle/ruby/2.3.0/bundler/gems/talon-one.rb-250227210621/lib/integration/client.rb" line 43 in update_customer_session
```

This is not a `RuntimeError` as it says. It is a `TalonOne::Integration::Client` error. I propose to implement a custom exception for this kind of errors. Would be nice if we can get a code or something that represents the exact problem that happened.

Here are the problematic line:
https://github.com/talon-one/talon_one.rb/blob/master/lib/integration/client.rb#L37

**Comment by cristianoliveira** [comment]
As soon I have some time I can do a PR for fixing this issue :)

**Comment by andrej-talon** [comment]
Hey :)

Thanks for letting us know. We are looking into it and will probably fix it soon. But if your PR is (close to) ready, you can commit it.

**Comment by TalonLaurens** [comment]
@cristianoliveira I made a simple pull request, can you check if this would be sufficient for your use case?

**Comment by cristianoliveira** [comment]
Hey @TalonLaurens

**Comment by cristianoliveira** [comment]
Hey @TalonLaurens 

That looks good. With that we can catch only the `TalonOne::Integration::ClientError` exceptions.

I know this is not with you guys but, in the future, would be even nicier if the API could give us a code with the errors, Something like this:

```ruby
begin
  response = client.update_costumer_session(attr)
rescue => e
  case e.cause
  when TalonOne::Integration::ClientError::MISSING_DATA
     # does stuff
  when TalonOne::Integration::ClientError::NOT_ALLOWED_STATE_CHANGE
     # other cool stuff
  when TalonOne::Integration::ClientError::OTHER_FOO_ERROR
     # so far so forth
end
```

**Comment by TalonLaurens** [comment]
Cool, I merged and pushed a new release to rubygems, should be available already :)

Thanks for your suggestion! I'll pass it on to our product team and we'll see if we can implement something like that in a future re-write of the SDK.

**Comment by cristianoliveira** [comment]
Thanks! :)
