### ISSUE TITLE
Updating to oj 2.18 breaks serialization

### ISSUE THREAD

**Issue by schmidt** [talon-one/talon_one.rb#8]
Since updating my dependencies in a Rails 5 project which uses the `talon_one` gem, I'm getting the following error when calling `client.close_customer_session`

```
NoMemoryError (Too deeply nested.)
```

I assume, this is basically the same problem as described in [this issue in the `oj` tracker](https://github.com/ohler55/oj/issues/325).

I could work around the problem by adding the following line to my `Gemfile`

```
gem 'oj', '~> 2.17.0'
```

Effectively avoiding the version of `oj`, which introduced the change. But since my project does not use the `oj` gem directly, I think, it's the talon_one gem's responsibility to handle this error/dependency.

N.B.: The error was only happening in our production environment, not locally.

**Comment by TalonLaurens** [comment]
Hey Gregor, thanks for this report.

We'll first look into making talon_one.rb compatible with oj 2.18 (and potentially even version 3+). If this proves too challenging, we'll limit the version in our gemspec.

You can expect an update from us early next week.

Best,

Laurens

**Comment by TalonLaurens** [comment]
I just ran a basic test using oj 2.18.5 and closing a customer session. I do not get any errors.

Do you guys have a stack trace or any further info you could share by any chance? It seems weird that this error occurs specifically when calling `close_customer_session`, as that API call has a very simple payload.

Thanks,

Laurens

**Comment by schmidt** [comment]
Thank you very much for the super quick response.

> I just ran a basic test using oj 2.18.5 and closing a customer session. I do not get any errors.
> 
> Do you guys have a stack trace or any further info you could share by any chance?

Unfortunately I don't have a stack trace. It's only happening in our staging environment, which uses the Rails production configuration (running on unicorn). I cannot reproduce the error locally in development mode. I think due to the nature of the bug, I don't get proper stack traces and our exception notifier also fails to generate proper reports.

> It seems weird that this error occurs specifically when calling close_customer_session, as that API call has a very simple payload.

I am not entirely sure, that it's really this one, since I don't have a proper stack trace (see above).

I'll try to come up with a minimal failing setup, that I can share. But for now it's not urgent since we've found a way to workaround the problem. My main intent in filing this issue was (a) raising awareness and (b) providing a possible workaround for others to follow, if necessary.

Cheers,

Gregor

**Comment by TalonLaurens** [comment]
Hey Gregor,

Based on your feedback and some educated guessing, we thing we managed to pin down the issue.

We just pushed a new version of the SDK to rubygems that should no longer cause this problem. It now requires Oj 3.0 but as you said nothing else in your codebase uses Oj, I guess that shouldn't be an issue.

Cheers,

Laurens

**Comment by schmidt** [comment]
Wow, this is awesome. Thanks. I'll give it a try in our setting soon.

Thanks for the great support.
